### ISSUE TITLE
Request method 'GET' not supported

### ISSUE THREAD

**Issue by username391** [GLEF1X/glQiwiApi#16]
При попытке совершить платеж через yoomoney все падает. Сервер возвращает ошибку "Request method 'GET' not supported" (во время второго запроса.
Нужно заменить http_method: ClassVar[str] = "GET" на "POST" в glQiwiApi/yoo_money/methods/process_payment.py чтобы все работало

**Comment by GLEF1X** [comment]
Кинь пул реквест, я смержу
