### ISSUE TITLE
Yoomoney API should support "OAuth2 client_secret"

### ISSUE THREAD

**Issue by VasiliyRusin** [GLEF1X/glQiwiApi#5]
In Yoomoney service creation interface you can choose "Verify app authenticity (OAuth2 client_secret)", it's not really a big deal to generate the right link by myself, but I think it should be "with batteries"

**Comment by GLEF1X** [comment]
Hi @VasiliyRusin

Thank you for your issue; I guess I will add it in the next version of glQIwiApi.

**Comment by GLEF1X** [comment]
**Fixed in 1.0.0 [click](https://github.com/GLEF1X/glQiwiApi/releases/tag/1.0.0)**
