### ISSUE TITLE
Referer (QIWI block)

### ISSUE THREAD

**Issue by progerg** [GLEF1X/glQiwiApi#9]
Hi. As I know (from June) QIWI block wallets users of which go to p2p pages from messengers, email and other services. QIWI needs referer. Is everything ok if I use glQiwiApi?

UPD: info from [here](https://github.com/WhiteApfel/pyQiwiP2P)

**Comment by GLEF1X** [comment]
Hi @GagikProger. This feature is not ready yet, but in 1.0.4 this will be added either as a separate project or in the package itself in the `glQiwiApi.ext` module.

**Comment by progerg** [comment]
Ok, thanks

**Comment by levkrll** [comment]
@GLEF1X
Tell me, plz. 
How to use referer?

**Comment by GLEF1X** [comment]
@levkrll @GagikProger 
[Here is the solution](https://glqiwiapi.readthedocs.io/en/latest/getting-started/qiwi/examples.html#issue-with-referrer), 2.0.0b1 is about to be released
